// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptsfvjokuvciszqsjwkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0c2Z2am9rdXZjaXN6cXNqd2ttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNDUxNDMsImV4cCI6MjA2NTkyMTE0M30.DSBWg8llFjhturkyvtVb8KLWbSikCmjEpTSAYZTjeA0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);